# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48706eae561f66d71f3f384b2ec6073cf29f4c1ec97a6c0033b7c667c127f19757a0a4485a3a9ee5b27069e58863eb5e777b618919aa5a92d26804635e794b5e

test:
  secret_key_base: 706665a440ab99f45e73829691753aa2e6520d6e84e15eddba5d8fe9bfddb73a3dfc15464da1749e97554cab594d9626670d52eab61e1134e4d7e2d7e99140c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
